[platformio]
src_dir = PlainFlightController
include_dir = PlainFlightController

[env:stable]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -I include/overrides
lib_deps =
    bblanchon/ArduinoJson@^7.4.3
    qqqlab/ESP32_SoftWire@^1.0.2

